services:
  librarymanagementdb:
    image: postgres:latest
    container_name: library-management-db-container
    environment:
      POSTGRES_DB: librarymanagementdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./database/postgresql-cfg:/etc/postgresql:ro"
      - "./database/postgresql-init:/docker-entrypoint-initdb.d:ro"